AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    currencies-api

    Api implementations for currencies

Globals:
    Function:
        Runtime: nodejs16.x
        Timeout: 180
        Handler: index.handler
        Environment:
            Variables:
                DB_NAME: currenciesdb
                DB_HOST: currenciesdbcluster-instance-1.cdtamzamlppu.us-east-1.rds.amazonaws.com
                DB_PORT: 5432
                DB_USER: postgres
                DB_PASSWORD: postgres123

Resources:
    Currencies:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: dist/
            Events:
                GetAllCurrencies:
                    Type: HttpApi
                    Properties:
                        Path: /currencies
                        Method: GET
                        Auth:
                            Authorizer: NONE
                GetCurrencyById:
                    Type: HttpApi
                    Properties:
                        Path: /currencies/{currencyId}
                        Method: GET
                        Auth:
                            Authorizer: NONE
                GetCurrencyByType:
                    Type: HttpApi
                    Properties:
                        Path: /currencies/types/{typeName}
                        Method: GET
                        Auth:
                            Authorizer: NONE
                IsValidTransaction:
                    Type: HttpApi
                    Properties:
                        Path: /currencies/pairs
                        Method: POST
                        Auth:
                            Authorizer: NONE

    APIIntegration:
        Type: AWS::ApiGatewayV2::Integration
        Properties:
            ApiId: !Ref Currencies
            Description: HTTP proxy integration
            IntegrationType: HTTP_PROXY
            IntegrationMethod: ANY
            PayloadFormatVersion: '2.0'
