import { document } from './documents/documentType';

// Generation
// Insomnia: $[?(@.type != "crypto")]
/* Node
c={}
a.map(b=>c[b.code.toUpperCase()]={min:b.minAmount, max: b.maxAmount, name: b.name})
*/
export const fiatData = {
  AUD: {
    min: 30,
    max: 16000,
    name: 'Australian Dollar',
    id: 'beb381fb-16d0-4949-890c-d78a626a0a8a',
  },
  BGN: {
    min: 40,
    max: 20000,
    name: 'Bulgarian Lev',
    id: '4372afed-961e-4c1c-9a8c-e922b2cb0ca5',
  },
  CAD: {
    min: 30,
    max: 16000,
    name: 'Canadian Dollar',
    id: '9efa0420-9f96-4b9c-a9ce-dee8e267ddcf',
  },
  CHF: {
    min: 20,
    max: 11000,
    name: 'Swiss Franc',
    id: '8508c57b-2720-4cb9-8d9f-2853ab52a091',
  },
  CNY: {
    min: 160,
    max: 82000,
    name: 'Chinese Yuan',
    id: '5465e43b-2596-48cc-b8de-b6de57421241',
  },
  COP: {
    min: 85000,
    max: 42500000,
    name: 'Colombian Peso',
    id: '2b7d4064-75fa-43c0-8fac-de57ea2f6980',
  },
  CZK: {
    min: 530,
    max: 260000,
    name: 'Czech Koruna',
    id: 'a865a512-0f4a-4147-9de2-4ed87717156c',
  },
  DKK: {
    min: 150,
    max: 75000,
    name: 'Danish Krone',
    id: 'b3e4e8f1-42b3-405b-994a-2bd1bd22786b',
  },
  DOP: {
    min: 1300,
    max: 680000,
    name: 'Dominican Peso',
    id: '1c6c3ff1-a796-4724-ae4c-449d1ef1897d',
  },
  EGP: {
    min: 350,
    max: 185000,
    name: 'Egyptian Pound',
    id: 'bdbcdf09-9896-49ca-bd5c-d1fb33f371bd',
  },
  EUR: {
    min: 20,
    max: 10000,
    name: 'Euro',
    id: '71435a8d-211c-4664-a59e-2a5361a6c5a7',
  },
  GBP: {
    min: 20,
    max: 9000,
    name: 'Pound Sterling',
    id: '6f424585-8936-4eb1-b01e-443fb306d1f5',
  },
  HKD: {
    min: 180,
    max: 90000,
    name: 'Hong Kong Dollar',
    id: 'a080db62-29b4-44d2-ad40-7fe037f72e5e',
  },
  HRK: {
    min: 150,
    max: 75000,
    name: 'Croatian Kuna',
    id: '68644263-38b4-43e3-b557-1370b041518c',
  },
  IDR: {
    min: 340000,
    max: 170000000,
    name: 'Indonesian Rupiah',
    id: 'a10ed157-1b7e-47ad-a3c9-fe6ae1ffff08',
  },
  ILS: {
    min: 80,
    max: 40000,
    name: 'Israeli New Shekel',
    id: '9a15ddd9-eed5-42b3-aae3-7589ee736985',
  },
  KES: {
    min: 2500,
    max: 1250000,
    name: 'Kenyan Shilling',
    id: '33c920d1-bdf0-42f6-aae1-397b92a459c5',
  },
  LKR: {
    min: 4300,
    max: 2150000,
    name: 'Sri Lankan Rupee',
    id: '83b57eca-5e25-4bd6-89bd-e4bada573bdb',
  },
  MAD: {
    min: 220,
    max: 110000,
    name: 'Moroccan Dirham',
    id: '456bc2e4-0219-4a19-8cfb-46291079c91b',
  },
  MXN: {
    min: 500,
    max: 260000,
    name: 'Mexican Peso',
    id: '6e703a57-0edb-49cc-84bc-c4d60a650b63',
  },
  MYR: {
    min: 100,
    max: 50000,
    name: 'Malaysian Ringgit',
    id: '87043a85-435b-4371-b201-9a4e97dcbb3c',
  },
  NGN: {
    min: 9000,
    max: 4500000,
    name: 'Nigerian Naira',
    id: '239495d6-1cb3-4fd0-bbe2-d3f15bf5f2ad',
  },
  NOK: {
    min: 200,
    max: 110000,
    name: 'Norwegian Krone',
    id: '82327c66-0f98-45fc-a212-b5bd709f9cc6',
  },
  NZD: {
    min: 40,
    max: 18000,
    name: 'New Zealand Dollar',
    id: '1c9beb30-cabb-40d5-aa28-f2ae703a42c0',
  },
  PEN: {
    min: 80,
    max: 40000,
    name: 'Peruvian Sol',
    id: '52d550cd-13eb-4a1c-b279-b68268c528a0',
  },
  PKR: {
    min: 3900,
    max: 1950000,
    name: 'Pakistani Rupee',
    id: '67b38247-8a2b-4614-a8fc-e078b3539cff',
  },
  PLN: {
    min: 90,
    max: 45000,
    name: 'Polish Złoty',
    id: '18dfd358-db55-43de-8660-826413bbc5ab',
  },
  RON: {
    min: 100,
    max: 48000,
    name: 'Romanian Leu',
    id: '1fecf3b1-7743-4b2e-89a7-7e32e6c64d13',
  },
  RUB: {
    min: 1500,
    max: 830000,
    name: 'Russian Ruble',
    id: 'b41ce2e4-383f-44d0-9cbe-d43a19f9671a',
  },
  SEK: {
    min: 200,
    max: 105000,
    name: 'Swedish Krona',
    id: '56ce4136-1519-469d-90e0-4c9cc9ddbe98',
  },
  SGD: {
    min: 30,
    max: 16000,
    name: 'Singapore Dollar',
    id: 'a403711c-39ba-4a1f-bee7-316c3af739f6',
  },
  THB: {
    min: 740,
    max: 370000,
    name: 'Thai Baht',
    id: 'b0eaa8d9-b197-4be1-8703-c0d42919bf57',
  },
  TRY: {
    min: 150,
    max: 80000,
    name: 'Turkish Lira',
    id: 'd3c98192-a872-4958-bc91-7a8434acc1d1',
  },
  TWD: {
    min: 680,
    max: 340000,
    name: 'Taiwan Dollar',
    id: '15618cb8-74ff-4af5-88cf-13c88271bbf3',
  },
  USD: {
    min: 20,
    max: 12000,
    name: 'US Dollar',
    id: 'edd81f1f-f735-4692-b410-6def107f17d2',
  },
  ZAR: {
    min: 400,
    max: 195000,
    name: 'South African Rand',
    id: '863cd8f3-e5d6-4ae8-b520-9cbb0e7713ad',
  },
} as { [fiat: string]: { max: number; min: number; name: string; id: string } };

// See https://support.moonpay.io/hc/en-gb/articles/360009279877-Who-can-use-MoonPay-
export const unsupportedCountries = [
  'al',
  'bs',
  'bd',
  'bb',
  'bo',
  'bw',
  'kh',
  'cn',
  'cu',
  'ec',
  'gh',
  'is',
  'ir',
  'jm',
  'mu',
  'mn',
  'mm',
  'ni',
  'kp',
  'pk',
  'pa',
  'ss',
  'sd',
  'sy',
  'ug',
  've',
  'ye',
  'zw',
];

// Also taken from https://support.moonpay.io/hc/en-gb/articles/360009279877-Who-can-use-MoonPay-
export const unsupportedUSAStates = [
  'CT',
  'HI',
  'IA',
  'KS',
  'KY',
  'MS',
  'NE',
  'NM',
  'NY',
  'RI',
  'WV',
  'AS',
  'GU',
  'MP',
  'VI',
];

// Generated from https://en.wikipedia.org/wiki/ISO_3166-2:US
export const USAStates = [
  'AL',
  'AK',
  'AZ',
  'AR',
  'CA',
  'CO',
  'CT',
  'DE',
  'FL',
  'GA',
  'HI',
  'ID',
  'IL',
  'IN',
  'IA',
  'KS',
  'KY',
  'LA',
  'ME',
  'MD',
  'MA',
  'MI',
  'MN',
  'MS',
  'MO',
  'MT',
  'NE',
  'NV',
  'NH',
  'NJ',
  'NM',
  'NY',
  'NC',
  'ND',
  'OH',
  'OK',
  'OR',
  'PA',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VT',
  'VA',
  'WA',
  'WV',
  'WI',
  'WY',
  'DC',
  'AS',
  'GU',
  'MP',
  'PR',
  'UM',
  'VI',
];

export const USsupportedCrypto = [
  { code: 'BCH', precision: 4 },
  { code: 'BTC', precision: 5 },
  { code: 'DAI', precision: 2 },
  { code: 'EOS', precision: 1 },
  { code: 'ETH', precision: 4 },
  { code: 'LTC', precision: 3 },
  { code: 'PAX', precision: 2 },
  { code: 'TUSD', precision: 2 },
  { code: 'USDC', precision: 2 },
  { code: 'USDT', precision: 2 },
  { code: 'XLM', precision: 0 },
  { code: 'XRP', precision: 0 },
];

// Ignore BORA and TOBA, they are irrelevant
export const supportedCryptoOutsideUS = [
  { code: 'ADA', precision: 1 },
  { code: 'ATOM', precision: 1 },
  { code: 'BAT', precision: 0 },
  { code: 'BNB', precision: 2 },
  // { code: 'BORA', precision: 3 },
  { code: 'BUSD', precision: 2 },
  { code: 'CELO', precision: 2 },
  { code: 'CHZ', precision: 0 },
  { code: 'CVC', precision: 0 },
  { code: 'DASH', precision: 3 },
  { code: 'DGB', precision: 1 },
  { code: 'DOGE', precision: 0 },
  { code: 'DROP', precision: 8 },
  { code: 'EOSDT', precision: 2 },
  { code: 'ERD', precision: 0 },
  { code: 'ETC', precision: 2 },
  { code: 'FUN', precision: 0 },
  { code: 'HBAR', precision: 1 },
  { code: 'HIVE', precision: 2 },
  { code: 'KAVA', precision: 2 },
  { code: 'LBC', precision: 3 },
  { code: 'LUNA', precision: 4 },
  { code: 'MANA', precision: 0 },
  { code: 'MIOTA', precision: 2 },
  { code: 'NANO', precision: 2 },
  { code: 'NEO', precision: 0 },
  { code: 'OKB', precision: 4 },
  { code: 'ONG', precision: 2 },
  { code: 'ONT', precision: 0 },
  { code: 'QTUM', precision: 3 },
  { code: 'RVN', precision: 1 },
  { code: 'SDT', precision: 4 },
  { code: 'SOL', precision: 2 },
  { code: 'SPICE', precision: 5 },
  { code: 'STMX', precision: 0 },
  // { code: 'TOBA', precision: 8 },
  { code: 'TRX', precision: 1 },
  { code: 'USDH', precision: 2 },
  { code: 'VET', precision: 0 },
  { code: 'WAVES', precision: 2 },
  { code: 'WAXP', precision: 0 },
  { code: 'XTZ', precision: 2 },
  { code: 'ZEC', precision: 5 },
  { code: 'ZIL', precision: 1 },
  { code: 'ZRX', precision: 2 },
];

/*
Generation script:
a={....} -> data from /countries
JSON.stringify(a.reduce((acc, c)=>({...acc, [c.alpha2]:c.supportedDocuments}), {}))
*/
export const requiredDocumentsAlpha2 = {
  af: ['passport', 'national_identity_card', 'residence_permit'],
  dz: ['passport', 'residence_permit'],
  ad: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ao: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ag: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ar: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  am: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  au: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  at: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  az: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  bh: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  by: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  be: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  bz: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  bj: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  bt: ['passport', 'residence_permit'],
  ba: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  br: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  bn: ['passport', 'driving_licence', 'residence_permit'],
  bg: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  bf: ['passport', 'driving_licence', 'residence_permit'],
  bi: ['passport', 'residence_permit'],
  cv: ['passport', 'driving_licence', 'residence_permit'],
  cm: ['passport', 'residence_permit'],
  ca: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  cf: ['passport', 'residence_permit'],
  td: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  cl: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  co: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  cg: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  cd: ['passport', 'driving_licence', 'residence_permit'],
  cr: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ci: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  hr: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  cy: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  cz: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  dk: ['passport', 'driving_licence', 'residence_permit'],
  dj: ['passport', 'driving_licence', 'residence_permit'],
  dm: ['passport', 'driving_licence', 'residence_permit'],
  do: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  eg: ['passport', 'residence_permit'],
  sv: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  gq: ['passport', 'national_identity_card', 'residence_permit'],
  ee: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  et: ['passport', 'residence_permit'],
  fj: ['passport', 'driving_licence', 'residence_permit'],
  fi: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  fr: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ga: ['passport', 'residence_permit'],
  gm: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ge: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  de: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  gr: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  gd: ['passport', 'driving_licence', 'residence_permit'],
  gt: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  gn: ['passport', 'residence_permit'],
  gw: ['passport', 'residence_permit'],
  gy: ['passport', 'driving_licence', 'residence_permit'],
  ht: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  hn: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  hk: ['passport', 'national_identity_card', 'residence_permit'],
  hu: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  in: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  id: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  iq: ['passport', 'residence_permit'],
  ie: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  il: ['passport', 'residence_permit'],
  it: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  jp: ['passport', 'residence_permit'],
  jo: ['passport', 'residence_permit'],
  kz: ['passport', 'driving_licence', 'residence_permit'],
  ke: ['passport', 'national_identity_card', 'residence_permit'],
  xk: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  kr: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  kw: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  la: ['passport', 'driving_licence', 'residence_permit'],
  lv: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  lb: ['passport', 'driving_licence', 'residence_permit'],
  ls: ['passport', 'residence_permit'],
  lr: ['passport', 'residence_permit'],
  ly: ['passport', 'residence_permit'],
  li: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  lt: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  lu: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  mg: ['passport', 'driving_licence', 'residence_permit'],
  mw: ['passport', 'driving_licence', 'residence_permit'],
  my: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  mv: ['passport', 'driving_licence', 'residence_permit'],
  ml: ['passport', 'driving_licence', 'residence_permit'],
  mt: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  mh: ['passport', 'driving_licence', 'residence_permit'],
  mr: ['passport', 'national_identity_card', 'residence_permit'],
  mx: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  fm: ['passport', 'residence_permit'],
  md: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  mc: ['passport', 'driving_licence', 'residence_permit'],
  me: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ma: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  mz: ['passport', 'national_identity_card', 'residence_permit'],
  na: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  nr: ['passport', 'residence_permit'],
  np: ['passport', 'driving_licence', 'residence_permit'],
  nl: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  nz: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ne: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ng: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  mk: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  no: ['passport', 'driving_licence', 'residence_permit'],
  om: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  pw: ['passport', 'residence_permit'],
  ps: ['passport', 'residence_permit'],
  pg: ['passport', 'driving_licence', 'residence_permit'],
  py: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  pe: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ph: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  pl: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  pt: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  qa: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ro: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ru: ['passport', 'driving_licence', 'residence_permit'],
  rw: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  kn: ['passport', 'driving_licence', 'residence_permit'],
  lc: ['passport', 'driving_licence', 'residence_permit'],
  ws: ['passport', 'residence_permit'],
  sm: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  st: ['passport', 'residence_permit'],
  sa: ['passport', 'driving_licence', 'residence_permit'],
  sn: ['passport', 'driving_licence', 'residence_permit'],
  rs: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  sc: ['passport', 'driving_licence', 'residence_permit'],
  sl: ['passport', 'driving_licence', 'residence_permit'],
  sg: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  sk: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  si: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  sb: ['passport', 'residence_permit'],
  so: ['passport', 'driving_licence', 'residence_permit'],
  za: ['passport', 'national_identity_card', 'residence_permit'],
  es: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  lk: ['passport', 'driving_licence', 'residence_permit'],
  sr: ['passport', 'driving_licence', 'residence_permit'],
  se: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ch: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  tw: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  tj: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  tz: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  th: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  tg: ['passport', 'residence_permit'],
  to: ['passport', 'driving_licence', 'residence_permit'],
  tt: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  tn: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  tr: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  tm: ['passport', 'driving_licence', 'residence_permit'],
  ua: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ae: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  gb: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  us: ['driving_licence', 'national_identity_card', 'residence_permit'],
  uy: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  uz: ['passport', 'driving_licence', 'residence_permit'],
  va: ['passport', 'residence_permit'],
  vn: ['passport', 'driving_licence', 'residence_permit'],
  eh: ['passport', 'residence_permit'],
  zm: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
} as { [country: string]: document[] };

/*
Generation script:
a={....} -> data from /countries
JSON.stringify(a.reduce((acc, c)=>({...acc, [c.alpha3]:c.supportedDocuments}), {}))
*/
export const requiredDocumentsAlpha3 = {
  AFG: ['passport', 'national_identity_card', 'residence_permit'],
  DZA: ['passport', 'residence_permit'],
  AND: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  AGO: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ATG: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ARG: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ARM: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  AUS: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  AUT: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  AZE: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  BHR: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  BLR: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  BEL: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  BLZ: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  BEN: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  BTN: ['passport', 'residence_permit'],
  BIH: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  BRA: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  BRN: ['passport', 'driving_licence', 'residence_permit'],
  BGR: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  BFA: ['passport', 'driving_licence', 'residence_permit'],
  BDI: ['passport', 'residence_permit'],
  CPV: ['passport', 'driving_licence', 'residence_permit'],
  CMR: ['passport', 'residence_permit'],
  CAN: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  CAF: ['passport', 'residence_permit'],
  TCD: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  CHL: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  COL: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  COG: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  COD: ['passport', 'driving_licence', 'residence_permit'],
  CRI: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  CIV: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  HRV: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  CYP: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  CZE: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  DNK: ['passport', 'driving_licence', 'residence_permit'],
  DJI: ['passport', 'driving_licence', 'residence_permit'],
  DMA: ['passport', 'driving_licence', 'residence_permit'],
  DOM: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  EGY: ['passport', 'residence_permit'],
  SLV: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  GNQ: ['passport', 'national_identity_card', 'residence_permit'],
  EST: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ETH: ['passport', 'residence_permit'],
  FJI: ['passport', 'driving_licence', 'residence_permit'],
  FIN: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  FRA: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  GAB: ['passport', 'residence_permit'],
  GMB: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  GEO: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  DEU: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  GRC: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  GRD: ['passport', 'driving_licence', 'residence_permit'],
  GTM: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  GIN: ['passport', 'residence_permit'],
  GNB: ['passport', 'residence_permit'],
  GUY: ['passport', 'driving_licence', 'residence_permit'],
  HTI: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  HND: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  HKG: ['passport', 'national_identity_card', 'residence_permit'],
  HUN: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  IND: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  IDN: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  IRQ: ['passport', 'residence_permit'],
  IRL: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ISR: ['passport', 'residence_permit'],
  ITA: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  JPN: ['passport', 'residence_permit'],
  JOR: ['passport', 'residence_permit'],
  KAZ: ['passport', 'driving_licence', 'residence_permit'],
  KEN: ['passport', 'national_identity_card', 'residence_permit'],
  XKX: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  KOR: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  KWT: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  LAO: ['passport', 'driving_licence', 'residence_permit'],
  LVA: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  LBN: ['passport', 'driving_licence', 'residence_permit'],
  LSO: ['passport', 'residence_permit'],
  LBR: ['passport', 'residence_permit'],
  LBY: ['passport', 'residence_permit'],
  LIE: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  LTU: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  LUX: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  MDG: ['passport', 'driving_licence', 'residence_permit'],
  MWI: ['passport', 'driving_licence', 'residence_permit'],
  MYS: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  MDV: ['passport', 'driving_licence', 'residence_permit'],
  MLI: ['passport', 'driving_licence', 'residence_permit'],
  MLT: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  MHL: ['passport', 'driving_licence', 'residence_permit'],
  MRT: ['passport', 'national_identity_card', 'residence_permit'],
  MEX: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  FSM: ['passport', 'residence_permit'],
  MDA: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  MCO: ['passport', 'driving_licence', 'residence_permit'],
  MNE: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  MAR: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  MOZ: ['passport', 'national_identity_card', 'residence_permit'],
  NAM: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  NRU: ['passport', 'residence_permit'],
  NPL: ['passport', 'driving_licence', 'residence_permit'],
  NLD: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  NZL: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  NER: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  NGA: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  MKD: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  NOR: ['passport', 'driving_licence', 'residence_permit'],
  OMN: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  PLW: ['passport', 'residence_permit'],
  PSE: ['passport', 'residence_permit'],
  PNG: ['passport', 'driving_licence', 'residence_permit'],
  PRY: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  PER: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  PHL: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  POL: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  PRT: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  QAT: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ROU: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  RUS: ['passport', 'driving_licence', 'residence_permit'],
  RWA: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  KNA: ['passport', 'driving_licence', 'residence_permit'],
  LCA: ['passport', 'driving_licence', 'residence_permit'],
  WSM: ['passport', 'residence_permit'],
  SMR: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  STP: ['passport', 'residence_permit'],
  SAU: ['passport', 'driving_licence', 'residence_permit'],
  SEN: ['passport', 'driving_licence', 'residence_permit'],
  SRB: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  SYC: ['passport', 'driving_licence', 'residence_permit'],
  SLE: ['passport', 'driving_licence', 'residence_permit'],
  SGP: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  SVK: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  SVN: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  SLB: ['passport', 'residence_permit'],
  SOM: ['passport', 'driving_licence', 'residence_permit'],
  ZAF: ['passport', 'national_identity_card', 'residence_permit'],
  ESP: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  LKA: ['passport', 'driving_licence', 'residence_permit'],
  SUR: ['passport', 'driving_licence', 'residence_permit'],
  SWE: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  CHE: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  TWN: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  TJK: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  TZA: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  THA: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  TGO: ['passport', 'residence_permit'],
  TON: ['passport', 'driving_licence', 'residence_permit'],
  TTO: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  TUN: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  TUR: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  TKM: ['passport', 'driving_licence', 'residence_permit'],
  UKR: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  ARE: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  GBR: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  USA: ['driving_licence', 'national_identity_card', 'residence_permit'],
  URY: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
  UZB: ['passport', 'driving_licence', 'residence_permit'],
  VAT: ['passport', 'residence_permit'],
  VNM: ['passport', 'driving_licence', 'residence_permit'],
  ESH: ['passport', 'residence_permit'],
  ZMB: [
    'passport',
    'driving_licence',
    'national_identity_card',
    'residence_permit',
  ],
} as { [country: string]: document[] };
